In [32]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
os.environ["XLA_FLAGS"] = "--xla_gpu_cuda_data_dir=/usr/lib/cuda"

In [ ]:
# !pip install -q --upgrade transformers huggingface_hub

In [ ]:
# !pip uninstall -y transformers huggingface_hub tokenizers

In [ ]:
# !pip uninstall -y transformers huggingface_hub tokenizers

In [ ]:
# !rm -rf /usr/local/lib/python3.12/dist-packages/transformers
# !rm -rf /usr/local/lib/python3.12/dist-packages/huggingface_hub
# !rm -rf /usr/local/lib/python3.12/dist-packages/tokenizers

In [ ]:
# !pip cache purge

In [ ]:
# !pip install -q transformers==4.44.2 huggingface_hub==0.34.4 tokenizers==0.19.1

In [1]:
!pip install -U transformers==4.44.2
!pip install -U tokenizers==0.19.1
!pip install -U huggingface_hub==0.34.4
!pip install sentencepiece sacremoses

Collecting transformers==4.44.2
  Downloading transformers-4.44.2-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.7 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (3.24.3)
Collecting huggingface-hub<1.0,>=0.23.2 (from transformers==4.44.2)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (2.32.4)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (0.7.0)
Collecting tokenizers<0.20,>=0.19 (from transformers==4.44.2)
  Downloading tokenizers-0.19.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.44.2) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.44.2) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.44.2) (1.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.44.2) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.44.2) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.44.2) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.44.2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.44.2) (2026.1.4)
Downloading transformers-4.44.2-py3-none-any.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 69.2 MB/s eta 0:00:00:00:010:01
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 35.0 MB/s eta 0:00:00
Downloading tokenizers-0.19.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 93.9 MB/s eta 0:00:00:00:01
Installing collected packages: huggingface-hub, tokenizers, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.4.1
    Uninstalling huggingface_hub-1.4.1:
      Successfully uninstalled huggingface_hub-1.4.1
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed huggingface-hub-0.36.2 tokenizers-0.19.1 transformers-4.44.2
Requirement already satisfied: tokenizers==0.19.1 in /usr/local/lib/python3.12/dist-packages (0.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers==0.19.1) (0.36.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.19.1) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.19.1) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.19.1) (1.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.19.1) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.19.1) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.19.1) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.19.1) (4.67.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers==0.19.1) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.16.4->tokenizers==0.19.1) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.16.4->tokenizers==0.19.1) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.16.4->tokenizers==0.19.1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.16.4->tokenizers==0.19.1) (2026.1.4)
Collecting huggingface_hub==0.34.4
  Downloading huggingface_hub-0.34.4-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.34.4) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.34.4) (2026.2.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.34.4) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.34.4) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.34.4) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.34.4) (4.67.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.34.4) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.34.4) (1.3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub==0.34.4) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub==0.34.4) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub==0.34.4) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub==0.34.4) (2026.1.4)
Downloading huggingface_hub-0.34.4-py3-none-any.whl (561 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 561.5/561.5 kB 10.6 MB/s eta 0:00:00a 0:00:01
Installing collected packages: huggingface_hub
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface_hub 0.36.2
    Uninstalling huggingface_hub-0.36.2:
      Successfully uninstalled huggingface_hub-0.36.2
Successfully installed huggingface_hub-0.34.4
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Collecting sacremoses
  Downloading sacremoses-0.1.1-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from sacremoses) (2025.11.3)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from sacremoses) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from sacremoses) (1.5.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sacremoses) (4.67.3)
Downloading sacremoses-0.1.1-py3-none-any.whl (897 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.5/897.5 kB 14.1 MB/s eta 0:00:00 0:00:01
Installing collected packages: sacremoses
Successfully installed sacremoses-0.1.1

In [2]:
from transformers import AutoTokenizer
print("✅ CLEAN ENV READY")

✅ CLEAN ENV READY

In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/her-will-ai-for-digital-safety-datathon-2026/sample_submission.csv
/kaggle/input/competitions/her-will-ai-for-digital-safety-datathon-2026/train.csv
/kaggle/input/competitions/her-will-ai-for-digital-safety-datathon-2026/test.csv

#import using https://github.com/Kaggle/kaggle-cli/blob/main/docs/competitions.md#kaggle-competitions-leaderboard

In [4]:
import os
import shutil

# delete old data folder
shutil.rmtree("data", ignore_errors=True)

# recreate
os.makedirs("data", exist_ok=True)

In [5]:
!kaggle competitions list

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.0), please consider upgrading to the latest version (2.0.2)
ref                                                                              deadline             category         reward  teamCount  userHasEntered
-------------------------------------------------------------------------------  -------------------  --------  -------------  ---------  --------------
https://www.kaggle.com/competitions/passenger-screening-algorithm-challenge      2017-12-15 23:59:00  Featured  1,500,000 Usd        518           False
https://www.kaggle.com/competitions/zillow-prize-1                               2018-01-10 15:59:00  Featured  1,200,000 Usd       3770           False
https://www.kaggle.com/competitions/data-science-bowl-2017                       2017-04-12 23:59:00  Featured  1,000,000 Usd       1972           False
https://www.kaggle.com/competitions/vesuvius-challenge-ink-detection             2023-06-14 23:59:00  Featured  1,000,000 Usd       1249           False
https://www.kaggle.com/competitions/arc-prize-2026-arc-agi-3                     2026-11-02 23:59:00  Featured    850,000 Usd        706           False
https://www.kaggle.com/competitions/arc-prize-2026-arc-agi-2                     2026-11-02 23:59:00  Featured    700,000 Usd        531           False
https://www.kaggle.com/competitions/gemini-3                                     2025-12-12 23:59:00  Featured    500,000 Usd       4095           False
https://www.kaggle.com/competitions/openai-gpt-oss-20b-red-teaming               2025-08-26 23:59:00  Featured    500,000 Usd        603           False
https://www.kaggle.com/competitions/openai-to-z-challenge                        2025-06-29 23:59:00  Featured    500,000 Usd        225           False
https://www.kaggle.com/competitions/arc-prize-2026-paper-track                   2026-11-09 23:59:00  Featured    450,000 Usd         34           False
https://www.kaggle.com/competitions/llm-prompt-recovery                          2024-04-16 23:59:00  Featured    200,000 Usd       2175           False
https://www.kaggle.com/competitions/vesuvius-challenge-surface-detection         2026-02-27 23:59:00  Research    200,000 Usd       1391           False
https://www.kaggle.com/competitions/asl-fingerspelling                           2023-08-24 23:59:00  Research    200,000 Usd       1314           False
https://www.kaggle.com/competitions/second-annual-data-science-bowl              2016-03-14 23:59:00  Featured    200,000 Usd        192           False
https://www.kaggle.com/competitions/kaggle-measuring-agi                         2026-04-16 23:59:00  Featured    200,000 Usd       1070           False
https://www.kaggle.com/competitions/gemma-4-good-hackathon                       2026-05-18 23:59:00  Featured    200,000 Usd        165           False
https://www.kaggle.com/competitions/datasciencebowl                              2015-03-16 23:59:00  Featured    175,000 Usd       1049           False
https://www.kaggle.com/competitions/data-science-bowl-2019                       2020-01-22 23:59:00  Featured    160,000 Usd       3493           False
https://www.kaggle.com/competitions/feedback-prize-2021                          2022-03-15 23:59:00  Featured    160,000 Usd       2058           False
https://www.kaggle.com/competitions/the-nature-conservancy-fisheries-monitoring  2017-04-12 23:59:00  Featured    150,000 Usd       2293           False

In [6]:
!kaggle competitions download her-will-ai-for-digital-safety-datathon-2026 -p data/ --force

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.0), please consider upgrading to the latest version (2.0.2)
Downloading her-will-ai-for-digital-safety-datathon-2026.zip to data
100%|██████████████████████████████████████| 2.67M/2.67M [00:00<00:00, 49.8MB/s]

In [7]:
import zipfile

with zipfile.ZipFile("data/her-will-ai-for-digital-safety-datathon-2026.zip", "r") as zip_ref:
    zip_ref.extractall("data/")
    
print("✅ Unzipped")

✅ Unzipped

In [8]:
import os

print(os.listdir("data/"))

['sample_submission.csv', 'test.csv', 'train.csv', 'her-will-ai-for-digital-safety-datathon-2026.zip']

In [9]:
import pandas as pd

train = pd.read_csv("data/train.csv")
test = pd.read_csv("data/test.csv")

print("Train shape:", train.shape)
print("Test shape:", test.shape)

train.head()

Train shape: (47817, 3)
Test shape: (11955, 2)

      id                                               text  y
0  38389  Woody Allen was expected to be there. If this ...  0
1  32893                                        বরগলা চোরের  0
2  32527                         খা বিমপি জামাত এর হারামিরা  0
3  19617  I'm happy the officer resigned. I saw one post...  1
4  25368  এ পাগল কুতারে কৈও বাদি রাকো নাহয় পাবনায় পাঠিয়ে...  0

#another way to import Data

In [10]:
import numpy as np
import pandas as pd

train = pd.read_csv('/kaggle/input/competitions/her-will-ai-for-digital-safety-datathon-2026/train.csv')
test = pd.read_csv('/kaggle/input/competitions/her-will-ai-for-digital-safety-datathon-2026/test.csv')
sample = pd.read_csv('/kaggle/input/competitions/her-will-ai-for-digital-safety-datathon-2026/sample_submission.csv')

print("✅ Data loaded")
print(train.shape, test.shape)
print(train.head())

✅ Data loaded
(47817, 3) (11955, 2)
      id                                               text  y
0  38389  Woody Allen was expected to be there. If this ...  0
1  32893                                        বরগলা চোরের  0
2  32527                         খা বিমপি জামাত এর হারামিরা  0
3  19617  I'm happy the officer resigned. I saw one post...  1
4  25368  এ পাগল কুতারে কৈও বাদি রাকো নাহয় পাবনায় পাঠিয়ে...  0

In [12]:
import torch
print(torch.cuda.is_available())

True

#part1-DEBUG

In [13]:
train.head()

      id                                               text  y
0  38389  Woody Allen was expected to be there. If this ...  0
1  32893                                        বরগলা চোরের  0
2  32527                         খা বিমপি জামাত এর হারামিরা  0
3  19617  I'm happy the officer resigned. I saw one post...  1
4  25368  এ পাগল কুতারে কৈও বাদি রাকো নাহয় পাবনায় পাঠিয়ে...  0

In [14]:
print(train.shape)
print(test.shape)

print(train.columns)
print(test.columns)

print(train["y"].value_counts())

(47817, 3)
(11955, 2)
Index(['id', 'text', 'y'], dtype='object')
Index(['id', 'text'], dtype='object')
y
0    23756
1    18163
2     5898
Name: count, dtype: int64

In [15]:
print(train.isnull().sum())
print(test.isnull().sum())

id      0
text    0
y       0
dtype: int64
id      0
text    0
dtype: int64

In [16]:
train.duplicated().sum()

np.int64(0)

In [17]:
train = train.dropna(subset=["text"])

In [18]:
train.sample(10)

          id                                               text  y
33037  48068                পিডাইয়া রাস্তা ক্লিয়ার করতে হবে ☠️👊  1
42314  34847  Israel will fuck up Usa like they try to fuck ...  0
39135   4784               হাফ লেডিস না হলে কি আর কানের দুল পরে  1
8922   10820  If you order clothes online & order several di...  0
692    30784              অসুবিধা নাই দুটোই সেকেন্ড হ্যান্ড মাল  1
41409   2656  লিখতে ভয় হচ্ছে তবুও লিখছি ।এমন খোলামেলা পোশাক...  2
13525  41533                  Stfu fake news, gat Damm lunatics  0
38856  57512    TMZ has turned into Kim Kardashian news network  0
35053  32797  ভোটের অধিকার বাতের অধিকার হরণ করে উন্নয়ন খুঁজ...  0
16379   9348  Haha. I would love to see the British governme...  0

In [89]:
# print(train["y"].value_counts(normalize=True))  # takes so much time+space

#dictionary for machine organized for it to learn

In [19]:
from sklearn.model_selection import train_test_split

train_texts, val_texts, train_labels, val_labels = train_test_split(
    train["text"].tolist(),
    train["y"].tolist(),
    test_size=0.1,
    random_state=42,
    stratify=train["y"]
)

print("✅ Split done")
print("Train:", len(train_texts))
print("Val:", len(val_texts))
# train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=128)   # only for one model, tokenizer seperated downward
# val_encodings = tokenizer(val_texts, truncation=True, padding=True, max_length=128)
# test_encodings = tokenizer(test["text"].tolist(), truncation=True, padding=True, max_length=128)

✅ Split done
Train: 43035
Val: 4782

In [ ]:
#HuggingFace Trainer
# from huggingface_hub import login

#GPU check+ kernel image

In [21]:
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

2.10.0+cu128
12.8
True
Tesla T4

#libraries

In [ ]:
# !pip install -U transformers

In [ ]:
# !pip install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
# !pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2

In [ ]:
# !pip install transformers accelerate datasets evaluate
# !pip install pip install torch==2.4.1+cu121 torchvision==0.19.1+cu121 torchaudio==2.4.1+cu121 --index-url https://download.pytorch.org/whl/cu121==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121
# !pip install torch==2.1.2+cu121 torchvision==0.16.2+cu121 torchaudio==2.1.2+cu121 \
#   --index-url https://download.pytorch.org/whl/cu121

In [84]:
# TrainingArguments(
#     no_cuda=True
# )

#tokenizer pipeline + getting students to our class

In [23]:
import os
os.environ["HF_HOME"] = "/kaggle/working/hf_cache"

In [24]:
from transformers import AutoTokenizer, AutoModel
from transformers import AutoModelForSequenceClassification

# ✅ DEFINE FIRST
tokenizer_xlmr = AutoTokenizer.from_pretrained(
    "xlm-roberta-base",
    force_download=True
)
model_xlmr = AutoModelForSequenceClassification.from_pretrained(
    "xlm-roberta-base",
    num_labels=3
)
# DeBERTa v3 (IMPORTANT: needs sentencepiece installed)
tokenizer_mdeberta = AutoTokenizer.from_pretrained(
    "microsoft/mdeberta-v3-base",
    force_download=True,
)
model_mdeberta = AutoModelForSequenceClassification.from_pretrained(
    "microsoft/mdeberta-v3-base",
    num_labels=3
)

print("✅ Tokenizers loaded")

# ✅ FAST SETTINGS 
MAX_LEN = 64

train_encodings_xlmr = tokenizer_xlmr(train_texts, truncation=True, padding="max_length", max_length=MAX_LEN)
val_encodings_xlmr   = tokenizer_xlmr(val_texts, truncation=True, padding="max_length", max_length=MAX_LEN)
test_encodings_xlmr  = tokenizer_xlmr(test["text"].tolist(), truncation=True, padding="max_length", max_length=MAX_LEN)

train_encodings_mdeberta = tokenizer_mdeberta(train_texts, truncation=True, padding="max_length", max_length=MAX_LEN)
val_encodings_mdeberta   = tokenizer_mdeberta(val_texts, truncation=True, padding="max_length", max_length=MAX_LEN)
test_encodings_mdeberta  = tokenizer_mdeberta(test["text"].tolist(), truncation=True, padding="max_length", max_length=MAX_LEN)

print("✅ Tokenization done")

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/579 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:551: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

pytorch_model.bin:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/mdeberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

✅ Tokenizers loaded
✅ Tokenization done

#part2-DEBUG

In [90]:
 # takes so much time+space#
# print("XLM-R keys:", train_encodings_xlmr.keys())
# print("mDeBERTa keys:", train_encodings_mdeberta.keys())

# print("Sample XLM-R length:", len(train_encodings_xlmr["input_ids"][0]))
# print("Sample mDeBERTa length:", len(train_encodings_mdeberta["input_ids"][0]))

# print("Train size:", len(train_encodings_xlmr["input_ids"]))
# print("Val size:", len(val_encodings_xlmr["input_ids"]))

#CREATE DATASETS to organize data

In [25]:
import torch

class SafetyDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

                #  HARD CHECK (prevents silent mismatch bugs)
        assert len(self.encodings["input_ids"]) == len(self.labels), "Mismatch!"

    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

    def __len__(self):
        return len(self.labels)

train_dataset_xlmr = SafetyDataset(train_encodings_xlmr, train_labels)
val_dataset_xlmr   = SafetyDataset(val_encodings_xlmr, val_labels)

train_dataset_mdeberta = SafetyDataset(train_encodings_mdeberta, train_labels)
val_dataset_mdeberta   = SafetyDataset(val_encodings_mdeberta, val_labels)

print("✅ Datasets ready")

✅ Datasets ready

#part3-DEBUG

In [26]:
print("✅ DATASETS CREATED")

print("XLM-R Train size:", len(train_dataset_xlmr))
print("XLM-R Val size:", len(val_dataset_xlmr))

print("mDeBERTa Train size:", len(train_dataset_mdeberta))
print("mDeBERTa Val size:", len(val_dataset_mdeberta))

✅ DATASETS CREATED
XLM-R Train size: 43035
XLM-R Val size: 4782
mDeBERTa Train size: 43035
mDeBERTa Val size: 4782

In [27]:
# 🔍 CHECK ONE SAMPLE 
sample = train_dataset_xlmr[0]
print("Sample keys:", sample.keys())
print("input_ids shape:", sample["input_ids"].shape)
print("attention_mask shape:", sample["attention_mask"].shape)
print("label:", sample["labels"])

Sample keys: dict_keys(['input_ids', 'attention_mask', 'labels'])
input_ids shape: torch.Size([64])
attention_mask shape: torch.Size([64])
label: tensor(0)

In [91]:
 # takes so much time+space#
# print("✅ Encoding type:", type(train_encodings_xlmr))
# print("✅ Keys:", train_encodings_xlmr.keys())
# print("Sample input_ids:", train_encodings_xlmr["input_ids"][0][:10])

#train em / exam

#part4-TRAIN FUNCTION -#F1METRICS

In [62]:
from transformers import TrainingArguments
import transformers

print("Transformers version:", transformers.__version__)
print("TrainingArguments from:", TrainingArguments.__module__)

Transformers version: 4.44.2
TrainingArguments from: transformers.training_args

In [63]:
import numpy as np
from transformers import TrainingArguments, Trainer
from sklearn.metrics import f1_score

In [64]:
import torch
# import torch.nn.functional as F
from transformers import Trainer

class WeightedTrainer(Trainer):
    def __init__(self, class_weights, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = class_weights

    def compute_loss(self, model, inputs, return_outputs=False):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits

        # 👇 THIS IS THE EXACT LINE YOU ASKED ABOUT
        loss_fct = torch.nn.CrossEntropyLoss(
            weight=self.class_weights.to(logits.device),
            label_smoothing=0.1   # ← ADD IT HERE
        )

        loss = loss_fct(logits, labels)
        return (loss, outputs) if return_outputs else loss

In [67]:
import numpy as np
from transformers import TrainingArguments, Trainer
from sklearn.metrics import f1_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {"f1": f1_score(labels, preds, average="macro")}
    
training_args = TrainingArguments(
    output_dir="./results",

    eval_strategy="steps",
    eval_steps=300,
    save_strategy="steps",   
    save_steps=300,          # 👈 match eval_steps
    save_total_limit=1,
    
    learning_rate=3e-5, #better+heavier obv
        # learning_rate=2e-5, 
    lr_scheduler_type="cosine",
    warmup_steps=500,
    max_grad_norm=1.0,

    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=4,   # even faster
    
    num_train_epochs=1,   # keep fast
    
    load_best_model_at_end=True,
    metric_for_best_model="f1",

    weight_decay=0.01,

    logging_steps=50,

    bf16=True,
    fp16=False, #(only if A100 / modern GPU — not always your case)

    dataloader_num_workers=2,
    
    report_to="none"
)

print("✅ Training setup ready")

# only logs during .train()
def train_model(model, train_dataset, val_dataset, tokenizer, name):
    print(f"\n🚀 Training {name}")

    trainer = WeightedTrainer(
        class_weights=class_weights,# ONLY here if your custom class supports it
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        tokenizer=tokenizer,# processing_class=tokenizer,
        compute_metrics=compute_metrics
    ) 

    trainer.train()
    result = trainer.evaluate()

    print(f"🏁 {name} RESULTS:", result)

    return trainer, result

✅ Training setup ready

In [68]:
import numpy as np
import torch
from sklearn.utils.class_weight import compute_class_weight

classes = np.unique(train_labels)

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=train_labels
)

class_weights = torch.tensor(class_weights, dtype=torch.float)

print("Class weights:", class_weights)

Class weights: tensor([0.6710, 0.8775, 2.7025])

In [69]:
# import os
# print(os.path.exists("./results"))
# !rm -rf ./results
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

!rm -rf ./results

#TRAIN BOTH MODELS

In [70]:
from transformers import AutoConfig, AutoModelForSequenceClassification

# XLM-R
config = AutoConfig.from_pretrained(
    "xlm-roberta-base",
    num_labels=3,
    hidden_dropout_prob=0.2,
    attention_probs_dropout_prob=0.2
)

model_xlmr = AutoModelForSequenceClassification.from_pretrained(
    "xlm-roberta-base",
    config=config
)
# model_xlmr = AutoModelForSequenceClassification.from_pretrained(
#     "xlm-roberta-base",   # faster than large
#     num_labels=3
# )

# # better F1
# model_xlmr.config.hidden_dropout_prob = 0.2
# model_xlmr.config.attention_probs_dropout_prob = 0.2

trainer_xlmr, result_xlmr = train_model(
    model_xlmr,
    train_dataset_xlmr,
    val_dataset_xlmr,
    tokenizer_xlmr,
    "XLM-R"
)

print("✅ XLM-R DONE")


# mDeBERTa
config_mdeberta = AutoConfig.from_pretrained(
    "microsoft/mdeberta-v3-base",
    num_labels=3,
    hidden_dropout_prob=0.2
)

model_mdeberta = AutoModelForSequenceClassification.from_pretrained(
    "microsoft/mdeberta-v3-base",
    config=config_mdeberta
)
# model_mdeberta = AutoModelForSequenceClassification.from_pretrained(
#     "microsoft/mdeberta-v3-base",
#     num_labels=3
# )

# # better F1
# model_mdeberta.config.hidden_dropout_prob = 0.2
# model_mdeberta.config.attention_probs_dropout_prob = 0.2

trainer_mdeberta, result_mdeberta = train_model(
    model_mdeberta,
    train_dataset_mdeberta,
    val_dataset_mdeberta,
    tokenizer_mdeberta,
    "mDeBERTa"
)

print("✅ mDeBERTa DONE")

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

🚀 Training XLM-R

🏁 XLM-R RESULTS: {'eval_loss': 1.065120816230774, 'eval_f1': 0.4552813430326285, 'eval_runtime': 35.3233, 'eval_samples_per_second': 135.378, 'eval_steps_per_second': 8.465, 'epoch': 0.9992565055762082}
✅ XLM-R DONE

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/mdeberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

🚀 Training mDeBERTa

🏁 mDeBERTa RESULTS: {'eval_loss': 1.0389121770858765, 'eval_f1': 0.4824679611432385, 'eval_runtime': 42.9791, 'eval_samples_per_second': 111.263, 'eval_steps_per_second': 6.957, 'epoch': 0.9992565055762082}
✅ mDeBERTa DONE

#COMPARE

In [72]:
print("\n📊 MODEL COMPARISON")
print("XLM-R F1:", result_xlmr["eval_f1"])
print("mDeBERTa F1:", result_mdeberta["eval_f1"])

if result_xlmr["eval_f1"] > result_mdeberta["eval_f1"]:
    best_trainer = trainer_xlmr
    best_name = "XLM-R"
    best_score = result_xlmr["eval_f1"]
else:
    best_trainer = trainer_mdeberta
    best_name = "mDeBERTa"
    best_score = result_mdeberta["eval_f1"]

print(f"🏆 Best model: {best_name}")
print(f"🔥 Best F1: {best_score:.4f}")

📊 MODEL COMPARISON
XLM-R F1: 0.4552813430326285
mDeBERTa F1: 0.4824679611432385
🏆 Best model: mDeBERTa
🔥 Best F1: 0.4825

#PREDICT TEST

In [73]:
# class TestDataset(torch.utils.data.Dataset):
#     def __init__(self, encodings):
#         self.encodings = encodings

#     def __getitem__(self, idx):
#         return {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}

#     def __len__(self):
#         return len(self.encodings["input_ids"])

from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")

train_texts, val_texts, train_labels, val_labels = train_test_split(
    train["text"].tolist(),
    train["y"].tolist(),
    test_size=0.1,
    random_state=42,
    stratify=train["y"]
)

print("✅ Split done")
print("Train size:", len(train_texts))
print("Val size:", len(val_texts))******************

In [76]:
# ========================
# 🔮 PREDICT ON TEST SET
# ========================

# pick correct encodings based on best model
if best_name == "mDeBERTa":
    test_dataset = TestDataset(test_encodings_mdeberta)
else:
    test_dataset = TestDataset(test_encodings_xlmr)

# run prediction
raw_preds = best_trainer.predict(test_dataset).predictions

import numpy as np
preds = np.argmax(raw_preds, axis=1)

print("✅ Predictions ready:", preds[:30])

✅ Predictions ready: [1 1 2 1 2 0 2 2 0 0 0 0 1 1 1 1 2 0 1 0 1 0 2 1 0 2 1 1 0 0]

In [85]:
# ========================
# 🔮 GENERATE PREDICTIONS
# ========================

test_dataset = TestDataset(test_encodings_mdeberta)

predictions = best_trainer.predict(test_dataset)
preds = np.argmax(predictions.predictions, axis=1)

print("✅ Predictions generated")

✅ Predictions generated

#SUBMISSION# for me-humanized-

In [93]:
# ========================
# 📊 HUMAN-READABLE OUTPUT
# ========================

label_map = {
    0: "toxic",
    1: "mid",
    2: "neutral"
}

pred_labels = [label_map[p] for p in preds]

import pandas as pd

results_df = pd.DataFrame({
    "text": test["text"],
    "predicted_id": preds,
    "predicted_label": pred_labels
})

results_df.to_excel("predictions.xlsx", index=False)

print("✅ Excel file ready")

# 👉 How to download:
# Look at the right sidebar
# Open “Output” tab under its path /kaggle/working/predictions.xlsx
# Find predictions.xlsx
# Click Download

✅ Excel file ready

#SUBMISSION# for competition

In [92]:
# ========================
# 📨 KAGGLE SUBMISSION (OPTIONAL)
# ========================

# Uncomment when you want to submit

import pandas as pd

sample = pd.read_csv('/kaggle/input/competitions/her-will-ai-for-digital-safety-datathon-2026/sample_submission.csv')

sample["y_pred"] = preds
sample.to_csv("submission.csv", index=False)

print("✅ Submission file ready")

✅ Submission file ready

In [88]:
# kaggle competitions submissions <competition-name>
!kaggle competitions submit \
-c her-will-ai-for-digital-safety-datathon-2026 \
-f submission.csv \
-m "baseline mDeBERTa (F1 ~0.48)"

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.0), please consider upgrading to the latest version (2.0.2)
100%|█████████████████████████████████████████| 138k/138k [00:00<00:00, 347kB/s]
Successfully submitted to HerWILL: AI for Digital Safety Datathon 2026